In [33]:
import pandas as pd

In [47]:
import numpy as np
from pandas import DataFrame

In [48]:
data = {
    'Uzbekistan':{2021:33.9, 2020:33.5, 2019:32.9, 2018:32.5, 2017:31.9},
    'Kazakhstan':{2021:18.9, 2020:18.7, 2019:18.5, 2018:18.3, 2017:18.1, 2016:17.8}
}
df2=DataFrame(data,index=[2021,2019,2017])
df2

Uzbekistan  Kazakhstan
2021        33.9        18.9
2019        32.9        18.5
2017        31.9        18.1

In [49]:
df2.T
df2

Uzbekistan  Kazakhstan
2021        33.9        18.9
2019        32.9        18.5
2017        31.9        18.1

In [50]:
df2=df2.T

In [51]:
df2

2021  2019  2017
Uzbekistan  33.9  32.9  31.9
Kazakhstan  18.9  18.5  18.1

In [52]:
df2.index.name=None


In [53]:
df2

2021  2019  2017
Uzbekistan  33.9  32.9  31.9
Kazakhstan  18.9  18.5  18.1

In [54]:

df2.T

Uzbekistan  Kazakhstan
2021        33.9        18.9
2019        32.9        18.5
2017        31.9        18.1

In [55]:
df2.values

array([[33.9, 32.9, 31.9],
       [18.9, 18.5, 18.1]])

In [56]:

df2.index

Index(['Uzbekistan', 'Kazakhstan'], dtype='object')

In [57]:
indeks=pd.Index([2015,2013,2009])

In [58]:


indeks

Int64Index([2015, 2013, 2009], dtype='int64')

In [59]:

indeks.difference(df2.index)

Int64Index([2009, 2013, 2015], dtype='int64')

In [60]:
indeks.drop(2013)

Int64Index([2015, 2009], dtype='int64')

In [61]:
'Turkiye' in df2.columns

False

In [62]:
'Uzbekistan' in df2.columns

False

In [102]:
usernames = {"anvar":"anvarbek223", "olim":"olimtoy", "maryam":"mary334455","javohir":"javohir445"}
emails = {"anvar":"anvar@gmail.com", "olim":"olim@mail.ru", "maryam":"mary33@gmail.com","javohir":"javohir445@gmail.com"}

data = {
    'username':usernames,
    'email':emails
}
df = pd.DataFrame(data)

In [64]:
df

username                 email
anvar    anvarbek223       anvar@gmail.com
olim         olimtoy          olim@mail.ru
maryam    mary334455      mary33@gmail.com
javohir   javohir445  javohir445@gmail.com

In [65]:
data2 = {
    'username':{"olim":"olimjon21", "maryam":"maryam2020"},
    'email':{"olim":"olimjon21@mail.ru", "maryam":"maryam20@gmail.com"}
}

In [68]:
df.append(DataFrame(data2))

<ipython-input-68-1514ca12eacb>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df.append(DataFrame(data2))


username                 email
anvar    anvarbek223       anvar@gmail.com
olim         olimtoy          olim@mail.ru
maryam    mary334455      mary33@gmail.com
javohir   javohir445  javohir445@gmail.com
olim       olimjon21     olimjon21@mail.ru
maryam    maryam2020    maryam20@gmail.com

In [71]:
df.index

Index(['anvar', 'olim', 'maryam', 'javohir'], dtype='object')

In [97]:
df3=df.append(DataFrame(data2))
df3

<ipython-input-97-e37c39831bb2>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3=df.append(DataFrame(data2))


username                 email
anvar    anvarbek223       anvar@gmail.com
olim         olimtoy          olim@mail.ru
maryam    mary334455      mary33@gmail.com
javohir   javohir445  javohir445@gmail.com
olim       olimjon21     olimjon21@mail.ru
maryam    maryam2020    maryam20@gmail.com

In [98]:
df3.index

Index(['anvar', 'olim', 'maryam', 'javohir', 'olim', 'maryam'], dtype='object')

In [99]:
df3.values

array([['anvarbek223', 'anvar@gmail.com'],
       ['olimtoy', 'olim@mail.ru'],
       ['mary334455', 'mary33@gmail.com'],
       ['javohir445', 'javohir445@gmail.com'],
       ['olimjon21', 'olimjon21@mail.ru'],
       ['maryam2020', 'maryam20@gmail.com']], dtype=object)

In [100]:
df3.columns

Index(['username', 'email'], dtype='object')

In [92]:
indeks.isin(df3.columns)

array([False, False, False])

In [93]:
df3['email']

anvar           anvar@gmail.com
olim               olim@mail.ru
maryam         mary33@gmail.com
javohir    javohir445@gmail.com
olim          olimjon21@mail.ru
maryam       maryam20@gmail.com
Name: email, dtype: object

In [94]:
df3.index.union(df2.index.union(indeks))

Index([        2009,         2013,         2015, 'Kazakhstan', 'Uzbekistan',
            'anvar',    'javohir',     'maryam',     'maryam',       'olim',
             'olim'],
      dtype='object')

In [95]:
df3.index.isnull()

array([False, False, False, False, False, False])

In [96]:
df3.index.unique()

Index(['anvar', 'olim', 'maryam', 'javohir'], dtype='object')

In [103]:
df3

username                 email
anvar    anvarbek223       anvar@gmail.com
olim         olimtoy          olim@mail.ru
maryam    mary334455      mary33@gmail.com
javohir   javohir445  javohir445@gmail.com
olim       olimjon21     olimjon21@mail.ru
maryam    maryam2020    maryam20@gmail.com

In [105]:
newindex=df3.index
newindex

Index(['anvar', 'olim', 'maryam', 'javohir', 'olim', 'maryam'], dtype='object')

In [107]:
newindex.sort_values()

Index(['anvar', 'javohir', 'maryam', 'maryam', 'olim', 'olim'], dtype='object')

In [108]:
newindex

Index(['anvar', 'olim', 'maryam', 'javohir', 'olim', 'maryam'], dtype='object')

In [112]:
df4=df3.index.unique()

In [113]:
df4

Index(['anvar', 'olim', 'maryam', 'javohir'], dtype='object')

In [114]:
data = {'Yil':[2021, 2020, 2019, 2018, 2017, 2016, 2015, 2010],
       'Aholi soni':[33.9, 33.5, 32.9, 32.5, 31.9, 31.4, 30.9, 28.5],
       'Temp':[1.54, 1.48, 1.56, 1.62, 1.65, 1.66, 1.64, 1.53],
       'Zichlik':[79.77, 78.68, 77.53, 76.34, 75.13, 73.91, 72.71, 67.03]}

In [115]:
df=DataFrame(data)
df

Yil  Aholi soni  Temp  Zichlik
0  2021        33.9  1.54    79.77
1  2020        33.5  1.48    78.68
2  2019        32.9  1.56    77.53
3  2018        32.5  1.62    76.34
4  2017        31.9  1.65    75.13
5  2016        31.4  1.66    73.91
6  2015        30.9  1.64    72.71
7  2010        28.5  1.53    67.03

In [116]:
df.index=[21,20,19,18,17,16,15,10]
df

Yil  Aholi soni  Temp  Zichlik
21  2021        33.9  1.54    79.77
20  2020        33.5  1.48    78.68
19  2019        32.9  1.56    77.53
18  2018        32.5  1.62    76.34
17  2017        31.9  1.65    75.13
16  2016        31.4  1.66    73.91
15  2015        30.9  1.64    72.71
10  2010        28.5  1.53    67.03

In [129]:
df = df.reindex(df.index.sort_values())

In [125]:
df.reindex([10,15,18])

Yil  Aholi soni  Temp  Zichlik
10  2010        28.5  1.53    67.03
15  2015        30.9  1.64    72.71
18  2018        32.5  1.62    76.34

In [130]:
df.reindex(columns=['Aholi soni','Zichlik'])

Aholi soni  Zichlik
10        28.5    67.03
15        30.9    72.71
16        31.4    73.91
17        31.9    75.13
18        32.5    76.34
19        32.9    77.53
20        33.5    78.68
21        33.9    79.77

In [131]:
df

Yil  Aholi soni  Temp  Zichlik
10  2010        28.5  1.53    67.03
15  2015        30.9  1.64    72.71
16  2016        31.4  1.66    73.91
17  2017        31.9  1.65    75.13
18  2018        32.5  1.62    76.34
19  2019        32.9  1.56    77.53
20  2020        33.5  1.48    78.68
21  2021        33.9  1.54    79.77

from matplotlib import pyplot as plt
df['Yil'].plot(kind='hist', bins=20, title='Yil')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df['Aholi soni'].plot(kind='hist', bins=20, title='Aholi soni')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df['Temp'].plot(kind='hist', bins=20, title='Temp')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df['Zichlik'].plot(kind='hist', bins=20, title='Zichlik')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df.plot(kind='scatter', x='Yil', y='Aholi soni', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df.plot(kind='scatter', x='Aholi soni', y='Temp', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df.plot(kind='scatter', x='Temp', y='Zichlik', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['Yil']
  ys = series['Temp']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = df.sort_values('Yil', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Yil')
_ = plt.ylabel('Temp')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['Yil']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'Yil'}, axis=1)
              .sort_values('Yil', ascending=True))
  xs = counted['Yil']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = df.sort_values('Yil', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Yil')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['Aholi soni']
  ys = series['Temp']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = df.sort_values('Aholi soni', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Aholi soni')
_ = plt.ylabel('Temp')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['Aholi soni']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'Aholi soni'}, axis=1)
              .sort_values('Aholi soni', ascending=True))
  xs = counted['Aholi soni']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = df.sort_values('Aholi soni', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Aholi soni')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
df['Yil'].plot(kind='line', figsize=(8, 4), title='Yil')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
df['Aholi soni'].plot(kind='line', figsize=(8, 4), title='Aholi soni')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
df['Temp'].plot(kind='line', figsize=(8, 4), title='Temp')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
df['Zichlik'].plot(kind='line', figsize=(8, 4), title='Zichlik')
plt.gca().spines[['top', 'right']].set_visible(False)

In [132]:
df.drop([15,16])

Yil  Aholi soni  Temp  Zichlik
10  2010        28.5  1.53    67.03
17  2017        31.9  1.65    75.13
18  2018        32.5  1.62    76.34
19  2019        32.9  1.56    77.53
20  2020        33.5  1.48    78.68
21  2021        33.9  1.54    79.77

In [133]:
df.loc[[10,15,20],['Aholi soni','Zichlik']]

Aholi soni  Zichlik
10        28.5    67.03
15        30.9    72.71
20        33.5    78.68

In [134]:
df

Yil  Aholi soni  Temp  Zichlik
10  2010        28.5  1.53    67.03
15  2015        30.9  1.64    72.71
16  2016        31.4  1.66    73.91
17  2017        31.9  1.65    75.13
18  2018        32.5  1.62    76.34
19  2019        32.9  1.56    77.53
20  2020        33.5  1.48    78.68
21  2021        33.9  1.54    79.77